# Generated by Django 3.0 on 2019-12-06 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('doors', models.IntegerField()),
                ('production_year', models.DateField()),
                ('body_type', models.CharField(choices=[('S', 'Sedan'), ('H', 'Hatchback')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('S', 'Sedan'), ('H', 'Hatchback')], max_length=15)),
                ('km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('color', models.CharField(max_length=10)),
                ('transmission', models.CharField(choices=[('A', 'Auto'), ('M', 'Manuel')], max_length=10)),
                ('plate', models.CharField(max_length=15)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('rent_ptice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rented_date', models.DateTimeField()),
                ('last_rented_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
