# Generated by Django 3.0 on 2019-12-07 08:39

from django.db import migrations, models
import django.db.models.deletion
import rent.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('E', 'Electric')], max_length=15),
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=rent.models.get_image_filename)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Car')),
            ],
        ),
    ]
